### ISSUE TITLE
Actions Tab Issues

### ISSUE THREAD

**Issue by zpsmith** [kontaktio/kontakt-beacon-admin-sample-app#11]
Hello Kontakt Team!

I have been looking and trying to use the Kontakt Beacon Admin Sample App found here: https://github.com/kontaktio/kontakt-beacon-admin-sample-app.

However, I have had issues getting actions to occur in the app. As stated in the ReadMe I have inserted my API Key into the code. I have also added an action to my beacons. Yet when I go to the "Actions" tab on the app, nothing happens when I type in my device unique id. I have tried this with the beacon's Proximity UUID, Instance ID, as well as the 4 character code on the back on the beacon, and none of these seem to trigger an action. Are none of these the correct ID that I should be entering?

Any assistance you could provide would be greatly appreciated,
Zane Smith

**Comment by michaldrabik** [comment]
@zpsmith Hi! Thanks for reaching out. The device unique ID is indeed a 4-chars code that you can find on the back of the Beacon and this is the one you should be entering. Also make sure that the action is assigned to correct Beacon in the web panel (try BROWSER action type with IMMEDIATE proximity, keep Beacon close to your device)

Let me know how it's going. If it's not working we will keep digging.

**Comment by zpsmith** [comment]
That is what we have been doing. We couldn't figure out if the app was
actually starting the scan for the UID. There is no UI to start that. Are
we missing something?

**Comment by michaldrabik** [comment]
At this moment the scanning starts when you open 'Actions' tab (there is no UI indication of that - it needs changing in the future). If the Bluetooth is turned off nothing is going to happen so make sure it is on. Also make sure that your device is connected to the internet. If that doesn't help please check if your Beacon appears in other tabs, for example 'Range all types'.
