### ISSUE TITLE
java.lang.NoClassDefFoundError: com.kontakt.sdk.android.http.KontaktApiClient

### ISSUE THREAD

**Issue by DaGeTian** [kontaktio/kontakt-beacon-admin-sample-app#13]
Hello, Everybody
I am developing Kontakt Beacons project now.
I will share my screen images.
<img width="881" alt="screen shot 2016-04-08 at 1 10 31 pm" src="https://cloud.githubusercontent.com/assets/14249806/14374711/a3ab3ef2-fd8b-11e5-8c72-7037b3ad5231.png">
<img width="1180" alt="screen shot 2016-04-08 at 1 10 57 pm" src="https://cloud.githubusercontent.com/assets/14249806/14374712/a3aedf26-fd8b-11e5-9e4b-d26b298fda46.png">
<img width="480" alt="screen shot 2016-04-08 at 1 11 11 pm" src="https://cloud.githubusercontent.com/assets/14249806/14374713/a3b03a9c-fd8b-11e5-92b2-8e3383d016a7.png">

KontaktSDK.initialize(this);

Initialize is working well.
But...

proximityManager = new KontaktProximityManager(this);
This is working without any errors on emulator.
But is appeared on real android phone.

How can i fix this problem?

**Comment by michaldrabik** [comment]
@DaGeTian Hello. Can you tell me what is your device and Android OS version? What version of Kontakt.io SDK are you using?

**Comment by DaGeTian** [comment]
I did like https://github.com/kontaktio/kontakt-beacon-admin-sample-app.

compile 'com.kontakt.sdk.android:kontakt.io-android-sdk:2.1.1'

And my device is EddyStone. Sample project is working fine. but not working background/foreground scan.

**Comment by michaldrabik** [comment]
@DaGeTian I was actually asking about your phone model and system version (Lollipop, Marshmallow or other?). 
So you are running our sample app (https://github.com/kontaktio/kontakt-beacon-admin-sample-app) on your phone and when you try foreground/background you get errors and app crashes. Am I understanding the problem correctly?

**Comment by DaGeTian** [comment]
https://github.com/kontaktio/kontakt-beacon-admin-sample-app is working fine on my phone.
first please leave foreground/background problem.
I am developing my project with EddyStone.

I just write in my project follow this.
- add to gradle
compile 'com.android.support:multidex:1.0.0'

- add to App.java
MultiDex.install(this);

after this I can create proximityManager(KontaktProximityManager).
but project has still error with kontakt.io.
If you want to look my state directly, I can share my screen through TeamViewer.
You can check it easily.

And then my phone version is Android 4.4.4(API19).

**Comment by michaldrabik** [comment]
Seems like your project is pretty big if you are using MultiDex. This might be the problem. Maybe you can try creating a new project (that only uses Kontakt.io SDK and no other libraries) just to see if everything works fine in that case.

**Comment by DaGeTian** [comment]
Thanks, It is working now.

**Comment by DaGeTian** [comment]
Hello, I have one problem with this sample project.
App can search Eddystones when restart phone and turn on bluetooth.
But after sometimes, App can't search anythings.
Logo is like follow this.

04-09 17:14:30.190 17572-16770/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:14:30.190 17572-2962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:14:30.580 17572-15774/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:14:40.900 17572-20357/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:14:50.910 17572-18962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:15:00.930 17572-2962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:15:10.540 17572-15774/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:15:10.570 17572-18962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:15:10.570 17572-2962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:15:10.580 17572-20357/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:15:10.970 17572-16770/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:15:21.290 17572-15774/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:15:31.320 17572-20357/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:15:41.320 17572-2962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:15:50.930 17572-16770/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:15:50.930 17572-15774/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:15:50.940 17572-20357/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:15:50.940 17572-2962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:15:51.320 17572-18962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:16:01.680 17572-16770/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:16:11.700 17572-15774/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:16:21.720 17572-2962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:16:31.330 17572-18962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:16:31.330 17572-16770/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:16:31.330 17572-15774/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:16:31.330 17572-2962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:16:31.730 17572-20357/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:16:42.040 17572-18962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:16:52.050 17572-16770/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:17:02.070 17572-15774/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:17:11.680 17572-20357/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:17:11.680 17572-18962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:17:11.680 17572-15774/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:17:11.680 17572-16770/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:17:12.080 17572-2962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:17:22.380 17572-20357/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:17:32.400 17572-18962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:17:42.430 17572-15774/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:17:52.040 17572-2962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:17:52.040 17572-20357/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:17:52.040 17572-18962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:17:52.040 17572-15774/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:17:52.440 17572-16770/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:18:02.760 17572-2962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:18:12.760 17572-18962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:18:22.780 17572-20357/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:18:32.400 17572-16770/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:18:32.410 17572-20357/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:18:32.410 17572-2962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:18:32.410 17572-18962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:18:32.810 17572-15774/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:18:43.140 17572-16770/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:18:53.150 17572-20357/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:19:03.170 17572-2962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:19:12.780 17572-15774/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:19:12.780 17572-16770/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:19:12.790 17572-2962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:19:12.790 17572-20357/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:19:13.180 17572-18962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:19:23.520 17572-20357/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:19:33.550 17572-15774/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:19:43.550 17572-16770/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:19:53.190 17572-18962/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:19:53.190 17572-20357/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:19:53.200 17572-16770/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:19:53.210 17572-15774/com.kontakt.sample D/BluetoothAdapter: startLeScan(): null
04-09 17:19:53.600 17572-2962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
04-09 17:20:03.910 17572-18962/com.kontakt.sample D/BluetoothAdapter: stopLeScan()
