### ISSUE TITLE
Secure beacons issue

### ISSUE THREAD

**Issue by ArabAgile** [kontaktio/kontakt-beacon-admin-sample-app#15]
Please take a look at this gist:
https://gist.github.com/ArabAgile/34c3dae64f70a78184d2654f38cb4243

I'm using secure beacons scanning as it's described in documentation: 

After fetching proximities using
`fetchProximities()`

I'm getting secure proximities only, which supposed to ignore other beacons (Not my beacons + my beacons but not secures 4.0 firmware), but unfortunately that's not the case:

```
List<IBeaconRegion> beaconRegions = new ArrayList<>();
        for (IProximityUUID proximityUUID : proximityUUIDs) {
            UUID realBleProximity = proximityUUID.**getSecureProximity()**; 
            beaconRegions.add(new BeaconRegion.Builder().setProximity(realBleProximity).build());
        }

        scanWithRegions(beaconRegions);
```

It's scanning for ALL beacons, not only secures and mine.

Is that a bug, or my implementation missing something?
Regards

**Comment by michaldrabik** [comment]
@ArabAgile Please add this `if` check in your code and let me know if that helps.

``` java
List<IBeaconRegion> beaconRegions = new ArrayList<>();
        for (IProximityUUID proximityUUID : proximityUUIDs) {
            UUID realBleProximity = proximityUUID.**getSecureProximity()**; 
            if(proximityUUID.isShuffled()) {
                beaconRegions.add(new BeaconRegion.Builder().setProximity(realBleProximity).build());
            }
        }

        scanWithRegions(beaconRegions);
```

**Comment by ArabAgile** [comment]
It worked! Thanks Michal!

But it's not clear at all in current documentation till date.

**Comment by michaldrabik** [comment]
It will be updated. Thanks.
