### ISSUE TITLE
How to resolve the Kontakt SDK? 

### ISSUE THREAD

**Issue by jun99999** [kontaktio/kontakt-beacon-admin-sample-app#18]
![image](https://cloud.githubusercontent.com/assets/20786078/17353282/abfd5d56-5970-11e6-9900-8cfef2c9c754.png)
![image](https://cloud.githubusercontent.com/assets/20786078/17353291/c3a11c04-5970-11e6-942c-5c1ca62188ee.png)
![image](https://cloud.githubusercontent.com/assets/20786078/17353297/d0a1865a-5970-11e6-967a-96fd58ee8b78.png)

**Comment by stoprocent** [comment]
Hi @jun99999. 

Can you please stop positing same issues multiple times? 
We are here to help but with issues regarding our SDK not general Android stuff. 

You have asked the same question (https://github.com/kontaktio/kontakt-beacon-admin-sample-app/issues/17) 1 hour before positing this one. 

Please try to keep our issues clean!
