### ISSUE TITLE
Android Application Sample not working

### ISSUE THREAD

**Issue by mrakha** [kontaktio/kontakt-beacon-admin-sample-app#2]
I have Kontakt beacons, and trying to use the code in the documentation and here to scan and display content on finding the beacon, but the problem is that the code provided is giving errors.

So please advise which part we can use to scan for beacons.

**Comment by dawidgdanski** [comment]
Could you please provide error you've received?

Downloading the project and importing with Android Studio does the trick.

**Comment by dawidgdanski** [comment]
Hey @mrakha  did you succeed?

**Comment by mail2bhramar** [comment]
Hi i want to find the beacon in background using started services of Android not bind services.i implemented your BeaconManager.MonitoringListener interface but not able to get response from your call back method.

**Comment by dawidgdanski** [comment]
Hey @mail2bhramar could you provide any code, please? Unfortunately there is little we can do  from raw description.

**Comment by dawidgdanski** [comment]
Hey @mail2bhramar is there anything I could be helpful with? Did you succeed in doing what you wanted to do?

**Comment by dawidgdanski** [comment]
@mail2bhramar I am closing this issue.
