### ISSUE TITLE
Read Beacon details and change Characteristics

### ISSUE THREAD

**Issue by Rkr999** [kontaktio/kontakt-beacon-admin-sample-app#20]
when trying to read beacon Characteristics it is calling onAuthenticationSuccess but RemoteBluetoothDevice.Characteristics are empty.

**Comment by michaldrabik** [comment]
What is your beacon's firmware version?

**Comment by Rkr999** [comment]
firmware version : 4.1.2.160620

**Comment by michaldrabik** [comment]
Ok, so Characteristics are only for beacons with firmwares 3.1 and older. You can ignore this if you use 4.0 or higher.

**Comment by Rkr999** [comment]
then how to read , write  interval and tx power from my app.

**Comment by michaldrabik** [comment]
Please check out **Kontakt.io Secure Communication** section: https://developer.kontakt.io/android-sdk/3.2.0/quickstart/#security

**Comment by Rkr999** [comment]
it showing cannot resolve method configsApi

**Comment by Rkr999** [comment]
hear configsApi() method not working

 cloud.configsApi().sender()
                .createConfig(config)
                .withType(DeviceType.BEACON)
                .forDevices("g0oQ")
                .send(new CloudCallback<Config[]>() {
                    @Override
                    public void onSuccess(Config[] response, CloudHeaders headers) {
                        fetchSecureCommunicationConfiguration();
                    }

                    @Override
                    public void onError(CloudError error) {

                    }
                });

**Comment by michaldrabik** [comment]
Documentation had a bug. It's now updated! Refresh and check out the code again

**Comment by Rkr999** [comment]
ok thanx

**Comment by Rkr999** [comment]
michaldrabik  this document is for write the data

**Comment by Rkr999** [comment]
first i need to read the txpower, advertising interval and put these two in edittext then when user click on button update these two details.

**Comment by michaldrabik** [comment]
For this you'll need to work with KontaktCloud (see API interactions section). Fetch beacon's data from the server, display to user, change it, send back to server to stay synced.

If you don't mind me asking. Why would you allow user to change those values. It seems weird to me.

**Comment by Rkr999** [comment]
ok not user merchant can change these settings from app. please can you send me example code.

**Comment by Rkr999** [comment]
i am not able to read the selected beacon  txpower and advertising interval please tell me how to do it.

**Comment by Rkr999** [comment]
thanks dude it working fine.
