### ISSUE TITLE
Beacon tags

### ISSUE THREAD

**Issue by androidprgmmer** [kontaktio/kontakt-beacon-admin-sample-app#22]
Hi,
Can we get the tag of the beacons programmatically which are given in the admin panel so that we can classify them according to the tags?

**Comment by michaldrabik** [comment]
@androidprgmmer There is a `getTags()` method in `Device` object that returns currently assigned tags. Devices can be fetched using the API or KontaktCloud in the SDK.

**Comment by robertbielas** [comment]
Closing, as it is an old issue.
