### ISSUE TITLE
Latest Version 4.0.2

### ISSUE THREAD

**Issue by jjimenez0611** [kontaktio/kontakt-beacon-admin-sample-app#24]
I have the version 4.0.0, and I try to upgrade to 4.0.2, but my grawdle says that not found this version. 
I only can upgrade to 4.0.1

**Comment by robertbielas** [comment]
@jjimenez0611 Your comment is old now, but if you are still interested: owing to bintray sunset, we migrated sdk hosting to Maven Central. The new version is 5.0.7. See updated build.gradle script of the sample app and changelog: https://knowledgebase.kontakt.io/mobile/android/changelog/. 5.0.7 does everything 4.0.2 does. 

Let us know if you have any troubles. Thanks!
