### ISSUE TITLE
Examples no longer valid with 4.0.2

### ISSUE THREAD

**Issue by MadisonBlake** [kontaktio/kontakt-beacon-admin-sample-app#25]
Changes in most recent Kontakt library make certian samples obsolete.

As an example
**KontaktDeviceConnection.ConnectionListener** created [here](
https://github.com/kontaktio/kontakt-beacon-admin-sample-app/blob/master/sample-app/src/main/java/com/kontakt/sample/samples/BeaconConfigurationActivity.java)

does not match the [documentation](
http://kontaktio.github.io/kontakt-android-sdk/4.0.2/Javadoc/com/kontakt/sdk/android/ble/connection/KontaktDeviceConnection.ConnectionListener.html)

**Comment by robertbielas** [comment]
@MadisonBlake Your comment is old now, but if you are still interested: examples were updated to point to the newest sdk 5.0.7. Documentation should not be mismatched (at least not when it comes to the example you provided). Please make sure to let us know if there are any other discrepancies. Thanks!
