### ISSUE TITLE
Delay in Service and Notification

### ISSUE THREAD

**Issue by MohamedNabil772** [kontaktio/kontakt-beacon-admin-sample-app#4]
I have Kontakt beacons, and trying to use the code in the documentation and here to scan and display content on finding the beacon, but the problem is that the service takes to much time to scan for beacon and same for notification when beacon appear.

As well after the scan is started and broadcast is build the problem that the Notification Broadcast Handler does not respond until the beacon is discovered  by Foreground Broadcast Handler at least once which defeats it's purpose.

So please advise what can be done to allow the Notification Broadcast Handler to start and not wait for the Foreground Broadcast Handler.

**Comment by dawidgdanski** [comment]
Hey @MohamedNabil772 , I have problems with understanding what you want to achieve. Broadcast Handlers process broadcasts coming from service, they just passively intercept messages and translate them for further usage: Toasts in foreground or Notifications in background. Do you want notifications being displayed regardless of whether the application is in foreground/background?

**Comment by MohamedNabil772** [comment]
That is the issue the notification broadcast handler is not starting to pickup and broadcasts coming from service until the Foreground Broadcast Handler works at least once.

The sequence is that the notification starts only after i make 1 successful foreground broadcast is handled and if the foreground broadcast is not made the app crashes
