### ISSUE TITLE
Missing layouts for some activity

### ISSUE THREAD

**Issue by fboesche** [kontaktio/kontakt-beacon-admin-sample-app#6]
I´m working on test your SDK 2.0 on Android Studio 1.3 and I found that RANGE and MONITOR beacons options and also SYNCABLE CONNECTION option is not showing any data when are selected. I think these is due to missing Activity layouts.

Hope these help to improve it.

Federico Boesche
federico@electronicacelular.com

**Comment by fboesche** [comment]
Hi, 
Checking with more detail, I realize that I am wrong in my previous comment (apologies). I think the problem I see is not related to layouts. But for some reason the option "RANGE BEACONS [EDDYSTONE]" does not work or show any information. I also find that the "SYNCABLE  CONNECTION" option is only defined for iBeacons and not for Eddystone beacons.

**Comment by dawidgdanski** [comment]
Hey @fboesche. As of release the Android SDK v2.0.0 we came up only with SyncableIBeaconConnection. Next versions of the sdk will bring the equivalent for Eddystone as well.

`But for some reason the option "RANGE BEACONS [EDDYSTONE]" does not work or show any information.`

Don't know what you mean by saying there is no information shown.
