### ISSUE TITLE
Get Beacon details onRegionAbandoned

### ISSUE THREAD

**Issue by anchitjindal91** [kontaktio/kontakt-beacon-admin-sample-app#9]
Hi i am referring current version of sample app everything is working fine but i just want to know in background scan can we get details of beacon which got abandoned. I need to monitor a particular beacon from its enter to abandoned. Can anyone please guide me how to do it?

**Comment by jakubkontakt** [comment]
Hi @anchitjindal91 

You can achieve that in very simple manner. Below is sample:

```
  @Override
        public void onEvent(BluetoothDeviceEvent bluetoothDeviceEvent) {
                switch (bluetoothDeviceEvent.getEventType()) {
                    case SPACE_ABANDONED:
                        if(bluetoothDeviceEvent instanceof IBeaconDeviceEvent) {
                            IBeaconDeviceEvent iBeaconDeviceEvent = (IBeaconDeviceEvent) bluetoothDeviceEvent;
                            IBeaconDevice iBeaconDevice = iBeaconDeviceEvent.getDeviceList().get(0);
                            //do your logic here
                        }

                        if(bluetoothDeviceEvent instanceof EddystoneDeviceEvent) {
                            EddystoneDeviceEvent eddystoneDeviceEvent = (EddystoneDeviceEvent) bluetoothDeviceEvent;
                            IEddystoneDevice eddystoneDevice = eddystoneDeviceEvent.getDeviceList().get(0);
                            //do your logic here
                        }
                        break;
                }
        }
```

**Comment by anchitjindal91** [comment]
Thanks for the reply. how can i use your code in foreground and background scan? As per sample code currently i am using following

```
protected abstract void onBeaconAppeared(final int info, final IBeaconDevice beaconDevice);

protected abstract void onRegionAbandoned(final int info, final IBeaconRegion region);

protected abstract void onRegionEntered(final int info, final IBeaconRegion region);
```

how can i replace these codes..

**Comment by jakubkontakt** [comment]
Are you sure that you are using SDK in version at least 2.0.0?

**Comment by anchitjindal91** [comment]
yes both app and repo dependencies.gradle file is same. And i recently clone it. Also i modify my last question please check again :)

**Comment by anchitjindal91** [comment]
oops sorry i miss "how" in my question please see the updated :P

**Comment by gauravsaini03-zz** [comment]
@jakubkontakt  Any update over this ?

**Comment by michaldrabik** [comment]
@gauravsaini03 @anchitjindal91 
Hello guys, I'll be taking over Jakub. 
If you could open a new issue for your problems that would be great. I don't know if this one has been resolved or not after all. Closing for now.
